### ISSUE TITLE
Output to line printer

### ISSUE THREAD

**Issue by thesailingengineer** [meri-imperiumi/signalk-logbook#42]
I'm trying to work on a signalk plugin to output a line of log text (very simple Lat/Lon, COG, SOG, Wind) to a line printer at a given time (every 15min or hour etc), so that if any electrical failure were to occur, the log would exitst in paper form. 
I have a 4" wide receipt printer and can send line of text by saving the text to /dev/usb/lp0.
I realise that 90% of what I am tying to achieve is already done by this plugin, so is it possible to add an option to send user defined values from the hourly log output to a user defined location (eg. /dev/usb/lp0)?

**Comment by bergie** [comment]
That's interesting! Can you share the hardware you're using?

As for implementing this in the plugin, that's certainly possible. Though you'd probably get it quicker by just doing a cronjob that reads the YAML log files

**Comment by thesailingengineer** [comment]
I bought a Star TSP800ii from ebay - it's not the cheapest (but still not expensive), but I wanted a 4" width to get a full useful log reading on a line. It runs from 24v and is quite fussy about this, so will need to get a 12- 24v converter for the boat, but for now it runs fine from a bench supply. 
Funny, before I started looking at signalk plugins I thought about using a cron job - but actually, maybe just tailing the YAML log with a little formatting would do the trick!
![20230419_221315](https://user-images.githubusercontent.com/131265648/233216663-ceed6447-f3b0-42d3-8147-884b09371255.jpg)
![20230419_221325](https://user-images.githubusercontent.com/131265648/233216672-1948ef8f-50f7-4fb5-aecd-02ccb3410066.jpg)
complete with a mock-up log I printed using `echo 'text' > /dev/usb/lp0`
It's amazingly simple, working out of the box with Linux, just needed CUPS disabling to stop it from blocking the port.
The idea came from the fact that my intentions are always good when I sail, and I do keep a paper log, but always forget to set an alarm for the hour, and end up missing log readings. When going further afield, it's a good back up should the electronics fail, hence the printer idea - then I found your plugin, which is amazing, and does literally everything I want (including autostart), but not the line printing bit - an old-fashioned idea, but one I think is ideal for boat usage!

**Comment by bergie** [comment]
@thesailingengineer can you give PR #44 a spin? Should do the trick, but obviously I don't have a printer here to test with.

**Comment by bergie** [comment]
Some more receipt printer ideas from aviation https://carloslagoa.com/blog/flipreps/flipreps.html

**Comment by bergie** [comment]
Ended up implementing this as a separate service:
https://github.com/meri-imperiumi/logbook-printer
