### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by martincaddick** [meri-imperiumi/signalk-logbook#57]
Just started 11 days ago and working out what I can do and I can go back and see the logs but it would be awesome if the viewing (in signalk) allowed a drop down or similar to let me change the number of days. Cheers

<img width="308" alt="image" src="https://github.com/meri-imperiumi/signalk-logbook/assets/73564857/51d793ba-4b6c-47f6-ab75-3531a6ad760f">

**Comment by bergie** [comment]
If you click that, it should allow you to change the number:
<img width="524" alt="Screenshot 2024-06-08 at 17 34 33" src="https://github.com/meri-imperiumi/signalk-logbook/assets/3346/3669eefe-57c3-4b88-bc1c-92a48bcaa4df">
