### ISSUE TITLE
How to modify #trip-end

### ISSUE THREAD

**Issue by Peter-Petrik** [meri-imperiumi/signalk-logbook#60]
Sometimes the sailing has not ended, even if the automated update of `navigation.state` by the signalk-autostate plugin indicates the boat as stopped. Could be dealing with an onboard issue while heaving-to, awaiting entrance to marina or bridge opening. Is there a way to remove the "Stopped" remark and join the two separate logbook entries?

**Comment by bergie** [comment]
Right now it's not an editable field, though that would be easy to change.

For the moment, easiest is to delete the trip end entry

**Comment by Peter-Petrik** [comment]
Say there are 20 entries for a specific day, effectively one trip with 15 entries and one with 5 entries. Entry 15 shows "Stopped". If I delete that one entry, does the logbook "join" the two trips into one with 19 entries?

**Comment by bergie** [comment]
The logbook is stateless, so if there is no "end" entry, then the trip is still ongoing

**Comment by Peter-Petrik** [comment]
That's great, thank you for the detailed explanation.
